# Generated by Django 4.2.6 on 2023-10-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'm_city',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='city-db-name-idx')],
                'unique_together': {('name',)},
            },
        ),
    ]
