# Generated by Django 4.2.6 on 2023-10-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('itinerary', models.CharField(max_length=2048)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city')),
            ],
            options={
                'db_table': 'm_itinerary',
                'ordering': ['day'],
                'indexes': [models.Index(fields=['day'], name='itinerary-db-name-idx')],
            },
        ),
    ]
